# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zL2mygWurYe8OF9IEbwsxHanlpeW9GN4
"""

import os

os.getcwd()

os.chdir('/content/drive/My Drive/ForksDay28')

import pandas as pd
train_data = pd.read_csv("iris_test.csv")

test_data = pd.read_csv("iris_test.csv")

features_train = train_data.iloc[:,0:4]
labels_train = train_data.iloc[:,4]

features_test = test_data.iloc[:,0:4]
labels_test = test_data.iloc[:,4]

train_data.head()

labels_train.head()

features_train.head()

classifier = Sequential()

classifier.add(Dense(units = 3, kernel_initializer = 'uniform', activation = 'relu', input_dim = 4))

classifier.add(Dense(units = 3, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(features_train, labels_train, batch_size = 5, epochs = 10)

labels_pred = classifier.predict(features_test)
labels_pred = (labels_pred > 0.5)

len(labels_pred)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

cm

labels_pred

